[package]
name = "arp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15.0"
gtk = { version = "0.5.1", package = "gtk4" }
